name: Test Action with Emails

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2005152@ds.study.iitm.ac.in
        run: echo "Hello, world! This is from my IITM email step 🎓"

      - name: Done!
        run: echo "Workflow executed successfully ✅"
